name: Bug
description: Report something that is not working as expected
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the bug clearly and concisely.
        Screenshots or recordings are very helpful.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What is happening?
      placeholder: "The galaxy view does not update after ending a year."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "The galaxy view should refresh and show updated positions."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can the bug be reproduced?
      placeholder: |
        1. Open galaxy view
        2. End the year
        3. Observe unchanged positions
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Anything that might help (view mode, selected entity, etc.)
      placeholder: "System view → back to galaxy, one army en route."
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Recordings
      description: Attach images or videos if available.
    validations:
      required: false
